"""Public package entry point for :mod:`swmmx`."""

from .api import SWMMModel, swmm
from .errors import (
    DependencyError,
    DimensionMismatchError,
    DuplicateIDError,
    EngineLoadError,
    EngineNotFoundError,
    EngineRunError,
    ExportError,
    ExportGeometryError,
    FormatError,
    InvalidPathError,
    InvalidParameterError,
    InvalidReferenceError,
    MissingRequiredParameterError,
    ModelNotRunError,
    NoPathError,
    NotImplementedYetError,
    ObjectNotFoundError,
    OptionalDependencyError,
    ParseError,
    PlotDataError,
    PlotError,
    ReadOnlyParameterError,
    ReferenceError,
    SaveError,
    SWMMXError,
    UnknownCategoryError,
    UnknownExportElementError,
    UnknownIDError,
    UnknownParameterError,
    ValidationError,
)

__all__ = [
    "DependencyError",
    "DimensionMismatchError",
    "DuplicateIDError",
    "EngineLoadError",
    "EngineNotFoundError",
    "EngineRunError",
    "ExportError",
    "ExportGeometryError",
    "FormatError",
    "InvalidPathError",
    "InvalidParameterError",
    "InvalidReferenceError",
    "MissingRequiredParameterError",
    "ModelNotRunError",
    "NoPathError",
    "NotImplementedYetError",
    "ObjectNotFoundError",
    "OptionalDependencyError",
    "ParseError",
    "PlotDataError",
    "PlotError",
    "ReadOnlyParameterError",
    "ReferenceError",
    "SaveError",
    "SWMMModel",
    "SWMMXError",
    "UnknownCategoryError",
    "UnknownExportElementError",
    "UnknownIDError",
    "UnknownParameterError",
    "ValidationError",
    "swmm",
]

__version__ = "0.0.10"
